---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - config.ru
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - Procfile
  - Rakefile
  - "**.erb"
  - "**.rb"
  - "**.css"
  - "**.coffee"
  - "**.js"
exclude_paths:
- 'bin/**/*'
- 'client/**/*'
- 'tmp/**/*'
- 'vendor/**/*'
- 'db/schema.rb'
