version: "2"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
exclude_patterns:
- 'bin/**/*'
- 'client/**/*'
- 'coverage/**/*'
- 'db/**/*'
- 'log/**/*'
- 'tmp/**/*'
- 'vendor/**/*'
