detectors:
  Attribute:
    enabled: false
  FeatureEnvy:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  IrresponsibleModule:
    enabled: false
  NestedIterators:
    max_allowed_nesting: 2
  NilCheck:
    enabled: false
  RepeatedConditional:
    max_ifs: 3
  TooManyInstanceVariables:
    max_instance_variables: 5
  TooManyMethods:
    enabled: false
  TooManyStatements:
    max_statements: 20
  UtilityFunction:
    enabled: false

exclude_paths:
  - db/
  - regression/
