# Uses defaults from https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# which is based on this ruby style guide https://github.com/bbatsov/ruby-style-guide

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'client/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'config/unicorn.rb'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
