# Schema documented at https://render.com/docs/yaml-spec
services:
  - type: web
    name: speedysportwhiz
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    region: ohio
    plan: free
    numInstances: 1
