version: 2
jobs:
  build:
    working_directory: ~/HockeyArena
    docker:
      - image: cimg/ruby:3.2.1-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - HockeyArena-{{ checksum "Gemfile.lock" }}
            - HockeyArena-
      - run:
          name: Install gems
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
            bundle check || bundle install
      - save_cache:
          key: HockeyArena-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run backend tests
          command: |
            bundle exec rake
      - run: bundle exec rubocop

workflows:
  version: 2

  commit:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
